server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb


application:
  inventory.path: '${inventory.path}'
  product.path: '${product.path}'

logging:
  level:
    com.pranitpatil : INFO
    org.springframework.web : DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m - %X{requestID}%n"