/*DROP TABLE IF EXISTS ArticleQuantity;
DROP TABLE IF EXISTS Article;
DROP TABLE IF EXISTS Product;*/

DROP ALL OBJECTS;

CREATE TABLE Article (
  id varchar(250)  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  stock INT NOT NULL default 0,
  CREATED_AT TIMESTAMP,
  LAST_MODIFIED_AT TIMESTAMP
);

CREATE TABLE Product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price DOUBLE default 10.00,
  CREATED_AT TIMESTAMP,
  LAST_MODIFIED_AT TIMESTAMP
);

CREATE TABLE ARTICLE_QUANTITY (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product VARCHAR(250) NOT NULL,
  articleId VARCHAR(250) NOT NULL,
  quantity INT NOT NULL,
  CREATED_AT TIMESTAMP,
  LAST_MODIFIED_AT TIMESTAMP
);